CREATE TABLE LOGIN(
ID INT AUTO_INCREMENT PRIMARY KEY,
EMAIL_ID VARCHAR(50) UNIQUE,
PASSWORD VARCHAR(50) NOT NULL
);


CREATE TABLE EMPLOYEES(
ID INT AUTO_INCREMENT PRIMARY KEY,
NAME VARCHAR(50),
GENDER VARCHAR(50),
MANAGER_ID INT ,
LOGIN_ID INT,
FOREIGN KEY (LOGIN_ID) REFERENCES LOGIN(ID),
FOREIGN KEY (MANAGER_ID) REFERENCES EMPLOYEES(ID)
);


CREATE TABLE LEAVES(
ID INT AUTO_INCREMENT PRIMARY KEY,
FROM_DATE DATE,
TO_DATE DATE,
APPLIED_DATE DATE,
STATUS ENUM('PENDING', 'APPROVED', 'REJECTED') NOT NULL DEFAULT 'PENDING',
EMPLOYEE_ID INT,
LOGIN_ID INT,
LEAVE_TYPE ENUM('SICK','CASUAL','MATERNITY','PATERNITY') NOT NULL,
LEAVE_COMMENT VARCHAR(200),
FOREIGN KEY (EMPLOYEE_ID) REFERENCES EMPLOYEES(ID),
FOREIGN KEY (LOGIN_ID) REFERENCES LOGIN(ID),
CHECK (FROM_DATE <= TO_DATE)
);


CREATE TABLE LEAVETYPE_MANAGEMENT(
LEAVE_TYPE ENUM('SICK','CASUAL','MATERNITY','PATERNITY') NOT NULL UNIQUE,
DAYS_ALLOWED INT
);

INSERT INTO LEAVETYPE_MANAGEMENT
(LEAVE_TYPE,DAYS_ALLOWED)
VALUES
('SICK',12),
('CASUAL',8),
('MATERNITY',180),
('PATERNITY',15);
